### ISSUE TITLE
Route choice hide & seek 

### ISSUE THREAD

**Issue by mrauturier** [NicoRio42/routechoice-db#13]
https://user-images.githubusercontent.com/23341782/173345992-aaf1eacb-20f1-46a4-93da-ad59c5b85a38.mov

See the video. When clicking on the map the RC disappear and it's hard to show it again. 

Expected:

Either click do nothing
or better click hide the current leg, click again show the leg again

**Comment by NicoRio42** [comment]
Not easily feasible cause it is the build in behavior of 2DRerun.
Will be fixed when (if ?) I ever get rid of 2DRerun and re-implement the mapviewer with openlayers.
